  version: '3.1'

  services:

    redis:
      image: huecker.io/library/redis
      ports:
        - "6379:6379"
      restart: always
      networks:
        - fairy_tales

    mongo:
      image: mongo
      restart: always
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_DATABASE: fairy_tales
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password
      networks:
        - fairy_tales

    mongo-express:
      image: mongo-express
      environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_MONGODB_PORT: 27017
        ME_CONFIG_MONGODB_ENABLE_ADMIN: true
        ME_CONFIG_MONGODB_AUTH_DATABASE: admin
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
        ME_CONFIG_BASICAUTH_USERNAME: root
        ME_CONFIG_BASICAUTH_PASSWORD: password
      links:
        - mongo
      ports:
        - "8081:8081"
      networks:
        - fairy_tales

  networks:
    fairy_tales: