<template>
  <div class="border border-solid border-gray-200 rounded-lg p-4">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pretium felis nunc, a porta tellus hendrerit porta. Nullam molestie risus quam, sit amet fermentum leo ornare at. Fusce tincidunt, tellus eget imperdiet mollis, nulla magna mollis est, et vulputate lectus sem ac erat. Curabitur eget elit vestibulum, facilisis ante id, egestas ligula. In eros eros, aliquet id laoreet elementum, faucibus at libero. Donec non nibh laoreet, hendrerit leo sit amet, scelerisque leo. Aliquam venenatis, nulla tempor auctor blandit, dui massa efficitur mi, sit amet congue sem lacus eget mauris. Sed egestas metus nisi, gravida finibus ex eleifend vel. Ut sed ex eget eros porta dictum. Maecenas quis risus dui.

    Suspendisse potenti. Nulla libero ex, tempus eget ultrices nec, placerat a velit. Donec eget dui ac urna sagittis imperdiet eget malesuada quam. Sed ligula diam, congue in aliquam sagittis, pellentesque sit amet enim. Pellentesque elit lorem, ullamcorper vel turpis eget, vulputate fermentum enim. Nullam luctus commodo nibh. Integer imperdiet felis vitae orci fermentum cursus ut at tortor. Nulla facilisi. Praesent non semper nulla. Phasellus feugiat vitae ex a elementum. Vestibulum non ullamcorper velit, sit amet scelerisque augue. Nulla facilisis accumsan dignissim. Vivamus at ligula eget elit blandit placerat.

    Quisque lacinia aliquam mollis. Donec in tellus ut nibh placerat elementum. Donec rhoncus cursus tortor ut gravida. Ut id diam ex. Donec eu lectus imperdiet, dictum leo a, tristique quam. Nulla vitae magna ut lectus congue aliquam. Fusce quis congue velit, at vehicula elit.

    Vivamus pulvinar eleifend quam. Proin in elementum tellus. Aliquam eget ornare justo. Maecenas vitae nulla consequat, efficitur urna eget, fringilla nunc. Quisque tempor, lorem sed dictum mollis, odio libero lobortis dui, hendrerit congue ligula tellus at mi. Vivamus nec lobortis ex. Sed eget malesuada leo. Morbi tincidunt, sem eget sagittis ultricies, dolor urna venenatis erat, sed gravida mi metus nec mi. Integer urna ligula, suscipit at venenatis eget, efficitur at purus. Nulla eget accumsan elit. Nullam facilisis mi purus, nec finibus justo euismod nec. Quisque dignissim arcu vitae varius viverra. Phasellus venenatis vitae libero ut semper. Nam dolor arcu, pellentesque nec fermentum et, feugiat suscipit libero. Aenean sagittis vestibulum consectetur. Donec sollicitudin quis nisi nec luctus.
  </div>
</template>